<?php

namespace School\AppBundle\Repository;

/**
 * CashRegisterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CashRegisterRepository extends \Doctrine\ORM\EntityRepository
{
}
