<?php

namespace School\AppBundle\Repository;

/**
 * ElevesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElevesRepository extends \Doctrine\ORM\EntityRepository
{
}
