<?php

namespace School\AppBundle\Repository;

/**
 * PayrecordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PayrecordRepository extends \Doctrine\ORM\EntityRepository
{
}
