<?php

namespace School\AppBundle\Repository;

/**
 * SpentRecordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpentRecordRepository extends \Doctrine\ORM\EntityRepository
{
}
